Bug fix for empty strings
ONSdigital/census-rm-toolbox pull request #101
Opened 2021-02-12 12:58 UTC by LeoKHoward

# Motivation and Context
Empty strings for FIELDCOORDINATOR_ID and FIELDOFFICER_ID were throwing up as invalid when encountering empty strings
This has only been added to non_compliance_processor.py in toolbox because the fields are not marked as mandatory in this script whereas they are elsewhere so empty strings would be caught by the mandatory() validator already

# What has changed
New validator to ignore empty strings
New test to check it works 

# How to test?
Validate a sample file with empty strings against FIELDCOORDINATOR_ID and/or FIELDOFFICER_ID

# Links
https://trello.com/c/WlOI0JYE

2021-02-12 12:59 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [bulknoncompliance validates FIELDCOORDINATOR_ID AND FIELDOFFICER_ID as mandatory when not mandatory](https://trello.com/c/WlOI0JYE/1964-bulknoncompliance-validates-fieldcoordinatorid-and-fieldofficerid-as-mandatory-when-not-mandatory)

2021-02-15 08:47 UTC, AdamHawtin requested changes
One comment, plus if you're adding a new validator it needs tests to prove valid ID's pass and invalid don't.

2021-02-15 08:47 UTC, AdamHawtin commented on toolbox/bulk_processing/validators.py
> +        if not stripped_field_value.isalnum() and stripped_field_value != "" or '':
```suggestion
        if not stripped_field_value.isalnum() and stripped_field_value != "":
```
Should just be this, the `or ''` is equivalent to `or False`.

2021-02-15 10:43 UTC, AdamHawtin commented on toolbox/tests/bulk_processing/test_validators.py
> +    alphanumeric_plus_hyphen_field_values_ignore_empty_strings_validator('')
Duplicate lines

2021-02-15 10:44 UTC, AdamHawtin requested changes
Just missing a test with a valid format ID

2021-02-16 08:36 UTC, AdamHawtin approved these changes

2021-02-16 09:43 UTC, NickGrantONS approved these changes
LGTM 👍

2021-02-16 09:45 UTC, merged