add qid linking functionality
ONSdigital/census-rm-toolbox pull request #18
Opened 2019-10-15 08:09 UTC by davidmort

## Context
We need to be able to manually link qids to cases via the questionnaire_linked event (mostly from community events that have taken place)

## What has Changed
Add a function to make_messae.py to put a questionnaire_linked event onto rabbit

## How to test
load a small sample
load a small unaddressed batch
pick a qid from the unaddressed batch and pick a case_id
use the toolbox to link them
you should see that uac_qid pair be linked to the caseref of that chosen case

# Links
https://trello.com/c/LYTqf5Ok/1272-community-event-pq-linking-14-10

2019-10-15 08:12 UTC, davidmort commented
![](https://github.trello.services/images/mini-trello-icon.png) [Community Event PQ linking - 14/10](https://trello.com/c/LYTqf5Ok/1272-community-event-pq-linking-14-10)

2019-10-15 08:24 UTC, NickGrantX requested changes
Can it use the Case API to verify that the Case actually exists? Ideally it would also check that the QID also exists too.

2019-10-15 08:26 UTC, davidmort commented
> Can it use the Case API to verify that the Case actually exists? Ideally it would also check that the QID also exists too.

yes good point, will add that in now

2019-10-15 10:45 UTC, NickGrantX approved these changes
Would be uber mega good if it also checked the QID existed before it sent the link message, but good enough - we'll just get bad messages which can't be processed if we input bad QIDs

2019-10-15 11:46 UTC, rjweeks approved these changes

2019-10-15 11:49 UTC, merged

2019-10-18 10:01 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add QID checksum tool to toolbox (3?)](https://trello.com/c/PLoxk1Ud/1284-add-qid-checksum-tool-to-toolbox-3)