Automate regional counts
ONSdigital/census-rm-toolbox pull request #20
Opened 2019-10-18 13:11 UTC by liamtoozer

# Motivation and Context

We need to automate regional counts for Census Rehearsal so we can grab the counts instead of having to run manual queries against the db.

# What has changed

* Added new query to gather regional counts
* Moved common SQL bits to helper function

# Links

https://trello.com/c/9e7YcwOO/1246-automate-regional-counts-3

2019-10-18 13:13 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Automate regional counts (3)](https://trello.com/c/9e7YcwOO/1246-automate-regional-counts-3)

2019-10-21 08:33 UTC, LukeLoze1 commented on regional_counts.py
> +-- AND action_plan_id = '432f0597-0076-4adb-834b-bf249dc06ded'
remove commented out sql

2019-10-21 08:35 UTC, liamtoozer commented on regional_counts.py
> +-- AND action_plan_id = '432f0597-0076-4adb-834b-bf249dc06ded'
Good spot, I was testing this locally 👍

2019-10-21 11:35 UTC, ryangrundy7 approved these changes
LGTM 👍

2019-10-21 13:41 UTC, LukeLoze1 approved these changes

2019-10-22 08:41 UTC, gavinleeedwards requested changes
I've just run the query in prod and it's splitting the England count - can't see why though!

2019-10-22 14:18 UTC, AdeHarrison approved these changes

2019-10-22 15:33 UTC, gavinleeedwards approved these changes
Looks good and all works fine in dev GCP environment 👍

2019-10-23 07:34 UTC, merged