Restore current project at end of WFH scripts
ONSdigital/census-rm-toolbox pull request #38
Opened 2020-03-25 08:39 UTC by NickGrantONS

# Motivation and Context
Running the WFH script leaves the current project as Black Lodge, which could be dangerous (i.e. mistakes could happen) and it's annoying.

# What has changed
Flip the project back at the end of the script.

# How to test?
Try it.

# Links
Trello: https://trello.com/c/jFApoTnR

2020-03-25 08:39 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [Set the context back after running whitelist WFH script](https://trello.com/c/jFApoTnR/752-set-context-back-after-running-whitelist-wfh-script)

2020-03-26 07:49 UTC, AdamHawtin requested changes
This sets the gcloud project back but still leaves `kubectl` pointing at Blacklodge.

2020-03-26 13:39 UTC, LukeLoze1 approved these changes
worked for me

2020-03-27 10:39 UTC, AdamHawtin approved these changes

2020-03-27 10:40 UTC, merged