Changes from classifiers to where_clause
ONSdigital/census-rm-toolbox pull request #50
Opened 2020-07-06 06:55 UTC by hbrace

# Motivation and Context

Classifiers have been changed to a where clause. This PR changes the batch reminders script for the new changes.

# What has changed

Json classifiers changes to sql where clauses. Script updated to handle this.
# How to test?

Build and deploy this pod, load a sample containing the treatment codes it needs (HH_LP1E, HH_LP1W, HH_LP2E, HH_LP2W), trying running the reminder batching script (follow README instructions.
Also trying running all the other tools to check for regression after the refactor (the script commands had to be changed to use module paths).
# Links

https://trello.com/c/TnldEmYZ/1023-address-frame-delta-generate-additional-initial-contact-files-13

2020-07-06 06:55 UTC, hbrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [Address Frame Delta - generate additional initial contact files (13)](https://trello.com/c/TnldEmYZ/1023-address-frame-delta-generate-additional-initial-contact-files-13)

2020-07-07 08:03 UTC, NickGrantX requested changes
`user_defined_where_clause` is still `classifiers` (or should be) - see other comments on PRs

2020-07-07 08:23 UTC, AdamHawtin requested changes

2020-07-07 08:23 UTC, AdamHawtin commented on reminder_batch_scheduler/reminder_batch.py
> +    wave_classifiers = {'where_clause': constants.WAVE_CLASSIFIERS[wave]}
Not sure why this is wrapped in a dictionary, it gets read out of it every place it's used that I could see

2020-07-07 11:38 UTC, AdamHawtin commented on test/reminder_batch_scheduler/test_reminder_batch.py
> +        'P_QU_H2': f'''case_type != 'HI' AND treatment_code IN ('HH_LP1W') AND print_batch IN ('{TEST_BATCH_COUNT}')'''
Not sure why these strings are triple quoted (style only) 💅

2020-07-07 11:39 UTC, AdamHawtin approved these changes

2020-07-07 13:14 UTC, NickGrantX approved these changes

2020-07-08 07:42 UTC, merged