1259 am bulk uninvalidate cases
ONSdigital/census-rm-toolbox pull request #68
Opened 2020-09-09 10:42 UTC by hbrace

# Motivation and Context

We need to mark cases as addressInvalid false from a file of case IDs sent from Address Management.

# What has changed

New bulk un-invalidate addresses bulk processor added and relevant config.

# How to test?

Get all repos with branches of the same name from the ticket. Build and deploy as necessary and run ATs with regression tests included.
Alternatively mark cases in your GCP env as `addressInvalid` and supply those caseIds to the bulk processor. Check they are now `addressInvalid=false`.
# Links

https://trello.com/c/yUW7p0OD/934-failure-mode-war-game-scenarios

2020-09-09 10:50 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [AM - uninvalidate cases (8)](https://trello.com/c/bbi2PO7z/1259-am-uninvalidate-cases-8)

2020-09-09 11:52 UTC, AdamHawtin commented on README.md
> +case_id
It's `CASE_ID` in the code

2020-09-09 13:59 UTC, hbrace commented on README.md
> +case_id
Silly me 🤦

2020-09-10 11:01 UTC, AdamHawtin requested changes

2020-09-10 11:01 UTC, AdamHawtin commented on toolbox/tests/bulk_processing/test_uninvalidate_address_processor.py
> +                          ('anything', 'BLAH'), ])
```suggestion
@pytest.mark.parametrize('case_id', ['test_case_id', 'TEST', 'anything', 'BLAH'])
```
You're currently only passing one parameter (`case_id`) in but the test cases are tuples of two so the second value is just being ignored.

2020-09-10 11:05 UTC, AdamHawtin commented on toolbox/tests/bulk_processing/test_uninvalidate_address_processor.py
> +@patch('toolbox.bulk_processing.bulk_processor.storage')
You should be able to get rid of this on all these tests and just pass in `patched_storage` to the test, this patching is already set up as a fixture in `../tests/bulk_processing/conftest.py`

2020-09-10 11:08 UTC, AdamHawtin commented on toolbox/bulk_processing/uninvalidate_address_processor.py
> +                "rmUnInvalidateAddress": {
Just spotted we'll have to be careful with this camel case, we treat `uninvalidate` as one word in most places but camel case it like two words.

2020-09-10 13:13 UTC, AdamHawtin approved these changes

2020-09-11 06:49 UTC, LukeLoze1 approved these changes

2020-09-18 10:54 UTC, merged